# Generated by Django 3.1.7 on 2021-03-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_username', models.CharField(max_length=120)),
                ('v_password', models.CharField(max_length=50)),
                ('v_orgid', models.CharField(max_length=10)),
            ],
        ),
    ]
