# Generated by Django 3.1.7 on 2021-03-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='v_orgid',
            new_name='orgid',
        ),
        migrations.RenameField(
            model_name='credential',
            old_name='v_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='credential',
            old_name='v_username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='credential',
            name='url',
            field=models.TextField(default='url'),
        ),
    ]
