# Generated by Django 3.1.7 on 2021-03-14 12:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_auto_20210314_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokenAdmin',
            fields=[
                ('accesstoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='verification.accesstoken')),
            ],
            bases=('verification.accesstoken',),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.TextField(blank=True, default=datetime.datetime(2021, 3, 14, 12, 37, 19, 151802), editable=False, max_length=5000),
        ),
    ]
