# Generated by Django 3.1.7 on 2021-03-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0012_auto_20210314_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
