# Generated by Django 3.1.7 on 2021-03-20 11:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0014_verificationlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='access_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NIN', 'NIN'), ('DEMO', 'DEMO'), ('BIO', 'BIO')], max_length=12, null=True),
        ),
    ]
