# Generated by Django 3.1.7 on 2021-03-20 11:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0015_accesstoken_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='access_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('nin', 'NIN'), ('demo', 'DEMO'), ('bio', 'BIO')], max_length=12, null=True),
        ),
    ]
