# Generated by Django 3.1.7 on 2021-03-20 12:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0016_auto_20210320_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='access_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('nin', 'NIN'), ('demo', 'DEMO'), ('phone', 'PHONE'), ('bio', 'BIO'), ('finger', 'FINGER SEARCH'), ('fingerV', 'FINGER VERIFICATION'), ('photoV', 'PHOTO VERIFICATION')], max_length=40, null=True),
        ),
    ]
