# Generated by Django 3.1.7 on 2021-03-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0017_auto_20210320_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.TextField(blank=True, default='do not edit. this field is autogenerated', max_length=5000, null=True),
        ),
    ]
