# Generated by Django 3.1.7 on 2021-03-26 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0018_auto_20210320_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(blank=True, default=0, max_length=5000, null=True)),
                ('access_type', models.CharField(blank=True, choices=[('nin', 'NIN'), ('demo', 'DEMO'), ('phone', 'PHONE'), ('bio', 'BIO'), ('finger', 'FINGER SEARCH'), ('fingerV', 'FINGER VERIFICATION'), ('photoV', 'PHOTO VERIFICATION')], default='nin', max_length=100, null=True)),
                ('direction', models.CharField(blank=True, choices=[('credit', 'CREDIT'), ('utilization', 'UTILIZATION')], default='credit', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
