# Generated by Django 3.1.7 on 2021-03-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0020_auto_20210326_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='direction',
            field=models.CharField(blank=True, choices=[('credit', 'CREDIT'), ('debit', 'DEBIT')], default='credit', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='units',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
