# Generated by Django 3.1.7 on 2021-04-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0022_auto_20210405_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='verification.unit')),
            ],
            bases=('verification.unit',),
        ),
        migrations.AlterModelOptions(
            name='credential',
            options={'verbose_name': 'NIMC eNVS Credential', 'verbose_name_plural': 'NIMC eNVS Credential'},
        ),
    ]
