# Generated by Django 3.1.7 on 2021-04-05 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0023_auto_20210405_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
