# Generated by Django 3.1.7 on 2021-04-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0024_auto_20210405_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationlogs',
            options={'verbose_name': 'Verification Log', 'verbose_name_plural': 'Verification Logs'},
        ),
    ]
