# Generated by Django 3.1.7 on 2021-04-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin_price', models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=10, null=True)),
                ('phone_price', models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=10, null=True)),
                ('demo_price', models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Prices',
            },
        ),
    ]
